name: simformat

ghc-options:
- -Wall
- -Werror
- -fwarn-tabs
- -O2

default-extensions:
- RecordWildCards

dependencies:
- base
- containers
- megaparsec >= 6.0.0

executables:
  simformat:
    main: main.hs
    source-dirs: ./

tests:
  simformat-doctests:
    main: doctests.hs
    dependencies:
    - doctest
