name: simformat
version: 0.1.0.0

ghc-options:
- -Wall
- -Werror
- -fwarn-tabs
- -O2

default-extensions:
- LambdaCase
- RecordWildCards
- OverloadedStrings

dependencies:
- base
- bytestring
- containers
- directory
- megaparsec >= 6.0.0
- optparse-applicative
- process
- text
- turtle
- yaml

library:
  source-dirs: src

executables:
  simformat:
    main: simformat.hs
    source-dirs: app
    dependencies:
    - simformat

tests:
  simformat-doctests:
    main: doctests.hs
    dependencies:
    - doctest
