name: simformat
version: 0.1.1.0
license: MIT
license-file: LICENSE
synopsis: Format Haskell source files.
description: Format Haskell source files according to convention at SimSpace - see the README
category: Language
github: Simspace/simformat

ghc-options:
- -Wall
- -Werror
- -fwarn-tabs
- -O2

default-extensions:
- LambdaCase
- RecordWildCards
- OverloadedStrings
- ScopedTypeVariables
- TupleSections

dependencies:
- base
- bytestring
- containers
- directory
- filepath
- megaparsec >= 6.0.0
- optparse-applicative
- process
- text
- turtle
- yaml

library:
  source-dirs: src

executables:
  simformat:
    main: simformat.hs
    source-dirs: app
    dependencies:
    - simformat

tests:
  test:
    main: main.hs
    source-dirs: test
    dependencies:
      - simformat

      - hspec
      - QuickCheck
      - unliftio

  simformat-doctests:
    main: doctests.hs
    dependencies:
    - doctest
