name: simformat
version: 0.0.0.2

ghc-options:
- -Wall
- -Werror
- -fwarn-tabs
- -O2

default-extensions:
- LambdaCase
- RecordWildCards
- OverloadedStrings

dependencies:
- base
- containers
- megaparsec >= 6.0.0
- optparse-applicative
- bytestring
- text
- turtle

library:
  source-dirs: src

executables:
  simformat:
    main: main.hs
    source-dirs: app
    dependencies:
    - simformat

tests:
  simformat-doctests:
    main: doctests.hs
    dependencies:
    - doctest
